### ISSUE TITLE
Issue with lauching application

### ISSUE THREAD

**Issue by tuanlinh281** [jobrunr/example-salary-slip#2]
I'm new to jobrunr. At the start of application I have this issue
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "JOBRUNR_MIGRATIONS" already exists;
I have tried stuffs but no use. Can somebody tell me what's wrong?

**Comment by rdehuyss** [comment]
Hi @tuanlinh281 , I just saw your issue now, sorry for that.

I updated the example to latest spring boot and the issue you're facing is solved as it now uses an in-memory datasource.

If you want to scale with multiple servers, you will of course need another database.
